### ISSUE TITLE
Compute net conversion of external metabolites

### ISSUE THREAD

**Issue by sthiele** [ARB-Lab/CNApy#53]
`net_conversion.m` uses `get_rates.m` which grabs the values from the CNA map.

**Comment by axelvonkamp** [comment]
In cobrapy metabolic models do not have any external metabolites, so I am not sure what this feature is supposed to do. The net conversion after e.g. performing an FBA is simply the flux values of the exchange reactions. Perhaps the reactions tab could have a sort option that places the exchange reactions at the top of the list so that they a grouped together.
